### ISSUE TITLE
Add `patternProperties`

### ISSUE THREAD

**Issue by Yash-Singh1** [schema-inspector/schema-inspector#121]
https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties

**Comment by mattwelke** [comment]
Just to clarify, when I made https://github.com/schema-inspector/schema-inspector/issues/109, I didn't mean I wanted us to add features to this library to make it equivalent to JSON schema validation libraries. I just wanted our documentation to explain to uses the difference. This library is currently used in a lot of legacy projects so it needs to be maintained but doesn't need new features added to it unless people explicitly ask for them and the community decides they make sense. New projects can choose to use this library because of how light weight it is compared to JSON schema libraries, but if we try to make it on par with JSON schema, then it loses that lightweight, simple appeal.

**Comment by Yash-Singh1** [comment]
These issues are not related to #109. I was trying to create issues that were described in the milestone: https://github.com/schema-inspector/schema-inspector/milestone/1

**Comment by mattwelke** [comment]
Oh that's super old. That was created by the original author years ago. And I think at this point we shouldn't attempt to match JSON schema functionality. We don't need to re-invent the wheel. I think we should keep the library maintained, secure, and embrace a light weight style of sanitization and validation.

**Comment by Yash-Singh1** [comment]
Sure, I will close the issues, but do you think adding references would be a good improvement?

**Comment by mattwelke** [comment]
@Yash-Singh1 
I don't think we need to support references in the schema because people can just use well-known software 
engineering techniques for code reuse to avoid writing duplicate schemas. We use this approach at my work where we use this library.

We have code like:

```js
const commonSchema = { // common stuff };

const schema1 = {
  commonStuff: commonSchema,
  specific: { // schema-specific stuff }
 };

const schema2 = {
  commonStuff: commonSchema,
  specific: { // schema-specific stuff }
 };
```

(psuedocode of course)

This works well because the recursive nature of the schemas here. We make subschemas for common parts of each schema we have and use a composition software engineering pattern to put it all together.
