### ISSUE TITLE
Email Pattern May Be Too Strict

### ISSUE THREAD

**Issue by joshwils82** [schema-inspector/schema-inspector#140]
It appears that the email pattern that was generated with email-regex-safe was done so with the gmail option enabled which results in a regex that prevents - and _.  I think this may be too strict for a general email validator.  Is it possible to regenerate the regex with the gmail option disabled?

Specifically, the gmail rules include the following 

can contain letters (a-z), numbers (0-9), and periods (.).
cannot contain an ampersand (&), equals sign (=), underscore (_), apostrophe ('), dash (-), plus sign (+), comma (,), brackets (<,>), or more than one period (.) in a row

https://github.com/spamscanner/email-regex-safe/blob/master/src/index.js#L40-L47

I believe underscore and dash should be allowed in the email.

**Comment by mattwelke** [comment]
Thanks for bringing this up. I wasn't aware it was too strict. In my opinion, it's not technically accurate to describe it as being an "email" validator if it says email addresses one can use outside of Gmail are invalid.

My proposed solution:

We do a minor release where we:

1) Change the regex for the email validation. We can re-run the process I described doing when I patched that CVE, and just disable the Gmail mode.

and

2) Copy the existing regex before the change described in 1 and call it "Gmail email validator" etc. That way people who need that strictness can still get it. I don't consider it a breaking change to change the default regex to be more flexible because we never advertised it as being a validator only for Gmail.

**Comment by mattwelke** [comment]
Interesting that my opinion today differs from how I felt the last time I proposed releasing a new version with less strict email regex:

> Version 2.0.0
> To fix a security vulnerability in the 1.x.x email Regex expression used, a new Regex expression was used which may be less flexible than the expression used in 1.x.x. Therefore, version 2.0.0 was released with this new expression. It's highly-recommended to upgrade to this new version after testing it.
> 
> If you need the old, insecure behavior, use version 1.x.x or use the custom validation function feature for your field and perform email address validation any way you like.

I'm starting to think releasing 2.0.0 instead of simply bumping the patch version last year was the wrong choice. It wasn't really a breaking change, it was a fix.

I'm curious what people think about this.

**Comment by joshwils82** [comment]
I like your proposed solution and think it would work well.  I was a bit surprised to see the gmail option as the default in email-safe-regex.

As a side note, it would be nice if it allowed supplying our own regex for some of the predefined patterns.  That way the caller could override them as they see fit.  I realize this is probably a larger feature but thought I would mention it.

**Comment by mattwelke** [comment]
Users could provide their own regex by using the basic "pattern" validator. The email validator is just a specialization of that.

https://github.com/schema-inspector/schema-inspector#v_pattern

**Comment by mattwelke** [comment]
Tried to fix this today, but I noticed that we had one of our unit tests fail after I switched the regex obtained with the code:

```js
const emailRegexSafe = require('email-regex-safe');
const regexString = emailRegexSafe({
    exact: true,
    returnString: true,
    gmail: false,
});
```

The issue was that the unit test had capital letters in it (`nikitajs@pantera.com`). For some reason, turning Gmail mode off disallowed capital letters. I googled a bit and found that email addresses should be considered valid if they have capital letters. Apparently, this is because email addresses are not case sensitive. So I'm a bit confused by this.

I made a bug report in email-regex-safe (https://github.com/spamscanner/email-regex-safe/issues/5).

**Comment by mattwelke** [comment]
@Yash-Singh1 I got a response in https://github.com/spamscanner/email-regex-safe/issues/5 from their devs on a suggested workaround. Would you mind giving this bug fix a shot? I know I took forever to merge in your other PRs. I'm sorry for that, it's not enough respect for your time. But if you're up for contributing still, I think I have time going forward to merge in a few PRs here and there. I don't think your effort would go to waste.

**Comment by Yash-Singh1** [comment]
I would love to work on this, but I am currently occupied with my school studies, so I don't have the time to look into this right now.

**Comment by mattwelke** [comment]
Planning on leaving this til 2023. It's pretty straightforward how to solve it, but it involves some regex work, updating tests, putting out a release, and it doesn't seem too urgent. Will speed it up if anyone mentions it being urgent.
