### ISSUE TITLE
Typescript feature request

### ISSUE THREAD

**Issue by onukwilip** [schema-inspector/schema-inspector#150]
Hello 👋🏾! My name is Prince. I just came across this awesome library, I'm developing a project using Node Js and Typescript. But, I noticed that there are no types definitions for the library, nor does it exist in the typescript @types registry. Please, is there an alternative available, I would really like to utilize this tool in my project😊?

**Comment by mattwelke** [comment]
Hi @onukwilip. Thanks for your suggestion.

This actually came up before in https://github.com/schema-inspector/schema-inspector/issues/69. I decided back then that it wasn't something we should do because the library is in my own sense of "maintenance mode". I took ownership of it a few years ago in order to quickly push out a security vulnerability fix, and since then I've kept an eye on it to fix things that need fixing. I'd like to continue on that path for now unless I get clear communication from people that the library is still useful to them compared to other data validation and sanitization libraries.

However, I can get you pointed in the right direction.

When it comes to TypeScript type definitions for libraries, there's generally a hierarchy of places developers can look to get them.

1) The library is written in TypeScript. You have the definitions because the TypeScript compiler produces them automatically as the authors publish it. This is great. It's the best option.
2) The library is written in JavaScript but the authors also make type definition files available alongside the published JavaScript files. This works well when the project authors don't want the library to be written in TypeScript, but they're willing to maintain type definition files.
3) The library is written in JavaScript and the community makes type definition files available via the DefinitelyTyped (aka "@types") project. This works well when the project authors aren't willing to support type definition files.
4) The library is written in JavaScript and the community does not yet make type definition files available via the DefinitelyTyped project.

> But, I noticed that there are no types definitions for the library, nor does it exist in the typescript https://github.com/types registry.

Right now, we're at step 4 in that hierarchy. And I see us being a good candidate project to move to step 3. I don't want us to move to steps 2 or 1 yet because I don't want the project to take on ownership of TypeScript related things in any way right now.

So, for you, I recommend getting in touch with the DefinitelyTyped project to either contribute types or request that other community members contribute them. A `@types/schema-inspector` package is the best place for them to be right now.

If you run into any issues, feel free to ping me and I'll do my best to help you get the ball rolling.
