### ISSUE TITLE
Sanitization "exec" does not set new value as "undefined"

### ISSUE THREAD

**Issue by hscasn** [schema-inspector/schema-inspector#71]
I am using the "exec" function on a property that checks if a string follows a certain pattern, if it does not, I want the property to be deleted (or become "undefined").

According to the documentation (https://github.com/Atinux/schema-inspector#s_exec), if I return "undefined", this will be the new value. This is not the behaviour I am getting: if I return undefined, the property just remains the same.

My schema is similar to this:

```
{
    type: 'string',
    optional: true,
    exec: (schema, post) => {
        if (isValid(post)) {
             return post;
        } else {
            return undefined;
        }
    },
}
```

**Comment by ViniciusFXavier** [comment]
BUG confirmed.

Thanks for the support @hscasn.

**Comment by Yash-Singh1** [comment]
Seems like the bug is fixed:

![Screen Shot 2021-04-08 at 9 37 43 AM](https://user-images.githubusercontent.com/53054099/114064031-15782b00-984e-11eb-93bd-024bfba09d50.png)

**Comment by mattwelke** [comment]
I don't think this should be closed yet. The behavior the reporter mentions is that the data isn't mutated the way they expect. The readme for this library is written in a way that suggests the sanitization is done by having `SchemaInspector.sanitize` mutate the data, not by using the data returned from that function call.

I was able to reproduce the bug for the use case of validating a string, like the reporter's use case:

![image](https://user-images.githubusercontent.com/7719209/114089407-1b88fe80-9884-11eb-998e-1f00b1a0b973.png)

**Comment by Yash-Singh1** [comment]
Taking a look @mattwelke's test cases and the source code, it seems as if the bug is still present and the bug is not `Sanitization "exec" does not set new value as "undefined"`, but it is `Sanitization "exec" does not set new value as "undefined" in "properties"`. The bug seems to be here:

https://github.com/schema-inspector/schema-inspector/blob/af0ea2762525bf3bfe086ab9ddd3be0229dafcf5/lib/schema-inspector.js#L993

and here:

https://github.com/schema-inspector/schema-inspector/blob/af0ea2762525bf3bfe086ab9ddd3be0229dafcf5/lib/schema-inspector.js#L1003
